name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libprom-dev libpromhttp-dev  # Instala las librerías Prometheus

    - name: Compile
      shell: bash
      run: |
        make all
