name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install libmicrohttpd-dev

    - name: Compile
      shell: bash
      run: |
        make all
