name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake make gcc libmicrohttpd-dev  # Dependencias para compilar las librerías

    - name: Install libprom from source
      shell: bash
      run: |
        git clone https://github.com/digitalocean/prometheus-client-c.git
        cd prometheus-client-c
        mkdir _build
        cd _build
        cmake ..
        make
        sudo make install  # Instala la librería

    - name: Compile
      shell: bash
      run: |
        make all
