name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libmicrohttpd-dev

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: .cache/lib
        key: ${{ runner.os }}-libcache-${{ hashFiles('**/path/to/dependencies/*') }}

    - name: Compile with CMake
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
  
